name: Check merged cert

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: macos-15

    steps:

    - name: Import Code Signing Certificates
      uses: apple-actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.APPLE_MERGED_CERTIFICATE }}
        p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        mobileprovision-base64: ${{ secrets.APPLE_PROVISIONING_PROFILE }

    - name: List Installed Certificates
      run: |
        echo "Listing installed certificates..."
        security find-identity -v -p codesigning
