name: Build and Deploy iOS App Project No Output

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: macos-15

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install MAUI Workloads
      run: dotnet workload install maui-ios

    - name: Decode and Install Apple Certificate
      env:
        APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
        APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      run: |
        echo "$APPLE_CERTIFICATE" | base64 --decode > certificate.p12
        security import certificate.p12 -P "$APPLE_CERTIFICATE_PASSWORD" -A

    - name: Decode and Install Provisioning Profile
      env:
        APPLE_PROVISIONING_PROFILE: ${{ secrets.APPLE_PROVISIONING_PROFILE }}
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "$APPLE_PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

    - name: List Installed Certificates
      run: |
        echo "Listing installed certificates..."
        security find-identity -v -p codesigning
    
    - name: Verify Entitlements File
      run: |
        if [ -f Platforms/iOS/Entitlements.plist ]; then
          echo "Entitlements.plist file found."
        else
          echo "Entitlements.plist file is missing."
          exit 1
        fi

    - name: Clean Build Artifacts
      run: dotnet clean PumpPad.csproj -c Release

    - name: Build iOS App
      run: dotnet publish PumpPad.csproj -f net8.0-ios -c Release --verbosity detailed

    - name: Inspect Entitlement File
      run: |
        echo "Inspecting Entitlements.xcent file..."
        cat obj/Release/net8.0-ios/ios-arm64/Entitlements.xcent || echo "Entitlements file not found."

    - name: Deploy to TestFlight
      env:
        APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        APPLE_API_ISSUER_ID: ${{ secrets.APPLE_API_ISSUER_ID }}
        APPLE_API_PRIVATE_KEY: ${{ secrets.APPLE_API_PRIVATE_KEY }}
      run: |
        echo "$APPLE_API_PRIVATE_KEY" | base64 --decode > AuthKey.p8
        xcrun altool --upload-app -f output/*.ipa \
          --type ios \
          --apiKey "$APPLE_API_KEY_ID" \
          --apiIssuer "$APPLE_API_ISSUER_ID"
