name: List iOS SDKs

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  list-ios-sdks:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List Available iOS SDKs
      run: xcodebuild -showsdks